import React from 'react'
import { useParams } from 'react-router-dom'


const UpdateProduct = () => {
    const id = useParams();
  return (
    <div>UpdateProduct
       <p>product id {id}</p>
       <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ipsum dolores, pariatur vel fuga dolor aut ipsa inventore! Pariatur debitis dolorum esse maxime aut distinctio, numquam officiis, repellendus repellat, voluptatibus ipsum?
       Totam, magni fugit iusto odio sapiente fuga repudiandae ducimus minus quidem molestias, tenetur doloribus architecto delectus consectetur qui accusamus deserunt inventore illum doloremque quae veritatis? Esse reprehenderit repudiandae tempore repellendus!
       Autem rerum, voluptates distinctio laboriosam labore animi. Fugit aut, voluptatem illo autem suscipit porro illum cupiditate vel esse voluptates excepturi sint corrupti repellendus molestias nam eligendi fuga aperiam dolor vero.
       Quam suscipit inventore quisquam repudiandae, cum ducimus voluptatibus debitis magni quidem nulla facere ad omnis nemo, nisi ex quia ratione amet nesciunt eius, eveniet vitae natus. Magnam nostrum doloribus voluptatibus.
       Assumenda sunt libero maxime tempora alias asperiores quas atque, reiciendis debitis, ab magni earum itaque at nisi non quam natus soluta voluptate eligendi. Quibusdam consequatur asperiores distinctio quo eos perspiciatis!
       Delectus laborum labore libero. Error corporis vero laboriosam fuga quam commodi velit quia. Consequatur ex in at quas explicabo sunt placeat sed, quia suscipit harum, ipsa ab quisquam delectus dolore.
       Iure dolorem nisi in commodi laudantium nam vitae expedita aliquid consectetur molestias iusto, ad veritatis officiis deleniti cum dolor obcaecati id eum laborum beatae, excepturi corporis natus! Et, sunt facilis?
       Sapiente expedita quis, magnam facere non laboriosam, aliquam nam quod vel libero explicabo inventore? Commodi aut culpa error ea accusantium expedita, vitae magni placeat maxime consequuntur dolores quaerat quae sapiente?
       Ad eos consequatur enim mollitia exercitationem suscipit totam. Sint magni illo ea minima, vel laudantium similique natus est at culpa incidunt, aspernatur blanditiis quasi sunt corrupti voluptatum ipsum tenetur. Placeat.
       Nam id at, vero recusandae placeat sunt quos ullam harum dolorem nihil aut, incidunt, dolor optio nesciunt itaque quia et voluptas minima mollitia? Voluptate ut fugit labore dolores magni architecto?
       Debitis ut quibusdam magnam velit eum. Sunt deserunt similique, eaque ratione earum quasi dolore voluptate, non laboriosam nihil ut culpa vitae. Impedit maxime nisi ut distinctio odit quas neque numquam!
       Cupiditate, quibusdam temporibus ullam nihil vitae cumque, ducimus perferendis, aliquid amet architecto voluptatibus vero! Cum libero quisquam, sed, esse tempora sit facilis unde sequi voluptas, accusamus temporibus cupiditate consequatur voluptate!
       Commodi, nam? Error delectus natus amet, ipsa facilis alias accusantium nulla a molestias quidem illo sint nihil repellendus corrupti eligendi dolorem officia dolorum hic. Ipsa minus voluptas cupiditate facere corporis.
       Pariatur architecto neque nemo sit corrupti quidem magnam iusto est, inventore ratione, magni distinctio dolore numquam nam reiciendis, voluptatibus sunt necessitatibus delectus repellat temporibus. Cum aut dolorum blanditiis officiis? Maxime!
       Veritatis eaque nemo similique voluptatem libero? Doloribus recusandae ipsa quos placeat adipisci debitis consectetur accusantium eius, libero sit aliquid nostrum commodi iste minima sed autem ut quo porro dolores corporis.
       Animi quibusdam, delectus sit recusandae, id officia non molestiae dolores quo quidem natus dolorum labore harum eveniet enim consequuntur accusamus ipsam illo architecto. Expedita, dolor quo vero recusandae blanditiis beatae?
       Ut eos exercitationem incidunt est eaque nihil quasi fuga temporibus rem veritatis impedit architecto fugiat fugit sed tenetur excepturi nulla iste unde modi, obcaecati distinctio. Tenetur deserunt dolorem nulla laudantium?
       Laboriosam necessitatibus excepturi iusto veritatis cumque repellat quasi iure accusamus nam quod tempora tenetur alias, ea dignissimos vitae vero ipsam. Voluptatibus earum voluptatem saepe possimus ipsam eveniet, eligendi pariatur quas?
       Itaque blanditiis quo saepe dolor quidem dolorem. Minus vel similique officia, labore ad qui accusamus, iste voluptas totam sint facere quod illum harum sunt, delectus rerum. Minima facilis vel maxime.
       Non perferendis laborum exercitationem corrupti necessitatibus? Quos, corporis similique? Natus laudantium vitae quibusdam asperiores, quam voluptatum eum odit quod molestiae voluptates debitis recusandae autem sapiente molestias labore consectetur vero repellat.
       Neque ratione porro deleniti assumenda quisquam minima animi exercitationem numquam vitae recusandae natus quam excepturi, autem corporis ea eius totam ipsum a iste laboriosam ullam iure qui provident repudiandae! Nulla.
       Neque in, laboriosam recusandae nostrum reiciendis repellat praesentium aspernatur dicta debitis quas, libero dolorem illum non nobis quam, veritatis consequuntur blanditiis expedita numquam vitae id inventore placeat ab reprehenderit! Atque?
       Animi voluptatibus doloremque explicabo delectus odio officiis quod, magni tempore. Earum, consequuntur tempore voluptas asperiores veniam sit impedit nisi amet, voluptatem placeat qui molestias reprehenderit tempora deserunt? Optio, temporibus adipisci!
       Tempora at eius ut exercitationem quia error, voluptates ex omnis aliquid beatae sit amet doloremque dolor dignissimos nulla provident rem ullam, sint voluptatibus eveniet debitis dolorem repellat? Sed, officia error?
       Repellendus fuga, provident odit voluptatibus, consequuntur blanditiis id aut illo quos harum labore cumque eius sint officiis veritatis facere nihil sit quibusdam nam, quasi qui voluptates unde ipsa assumenda? Reiciendis!
       Dolore eius sapiente reprehenderit, eligendi voluptate nemo magni modi dolorem accusantium impedit, fugiat, tenetur et sint. Fuga minus consequuntur, mollitia aliquam dicta voluptas quam odit quas dolorem. Laboriosam, necessitatibus fuga?
       Nisi exercitationem, fugiat incidunt eum illum rerum labore blanditiis aliquid excepturi aliquam quibusdam ipsa praesentium sapiente dolor libero nemo soluta veritatis suscipit sunt, ratione voluptates in. Vero repudiandae necessitatibus praesentium!
       Labore officiis quam repellendus? Dolores sapiente, at consequatur consequuntur amet rem magnam labore, eum, quisquam sequi facere ad in nemo nisi libero harum beatae. Cumque quisquam magnam mollitia voluptas. Harum?
       Dolorem culpa error dolore dolorum velit quo, architecto ut rerum, hic ex fuga ratione iure corporis libero, delectus ducimus facilis voluptate nemo beatae! Nobis odio dolor possimus labore accusantium voluptas.
       Maxime, esse a, ipsam consequatur modi corrupti recusandae exercitationem consectetur provident at tempore laborum fuga numquam veritatis inventore. Reiciendis nemo animi voluptate harum natus repellat ut cupiditate nostrum non doloremque.
       Dolorum non nostrum voluptatum atque maiores voluptates molestias quia, nemo tenetur ex, deserunt eos corporis at accusantium. Labore incidunt cum voluptatem id dolorem quia quod. Est modi sapiente harum. Quia?
       Sapiente ullam autem quos unde ea harum! Alias officia nisi expedita facere praesentium? Illum, iure unde harum aliquid accusamus qui quo accusantium impedit a. Libero non quod nobis magni nulla!
       Eum dicta cupiditate corrupti incidunt nihil ex maxime atque suscipit explicabo aut cumque libero voluptas minus mollitia officiis consequatur quisquam, blanditiis, vitae saepe ab ad illo asperiores perspiciatis exercitationem. Quaerat!
       Nostrum recusandae nesciunt ab cumque totam maxime adipisci assumenda, eum earum magnam minima perferendis consectetur soluta eius fugit doloribus ipsum, accusantium quia, natus dicta architecto fugiat ullam. Veniam, fugit dolorum.
       Harum quidem repudiandae distinctio quis aperiam nobis, assumenda reprehenderit animi commodi iure, rerum, esse soluta corporis eaque. Voluptatum nobis debitis architecto velit dolores accusamus, consectetur, necessitatibus laboriosam quis, eveniet et!
       Iusto explicabo, deserunt ipsum rem fugit ad possimus. Atque dicta, sapiente, modi vel sequi suscipit minima, beatae sint dolorem voluptas quam totam nulla! Tenetur accusamus in temporibus dolor similique dicta.
       Minus, vero quos. Porro laudantium molestias natus quos cupiditate eveniet, harum qui soluta modi ad nesciunt quaerat mollitia ea dignissimos! A veritatis ea illo minus modi voluptate non ad aliquam.
       Obcaecati mollitia est itaque dicta repellat rerum atque optio id, placeat soluta labore quae rem eos, fugiat possimus suscipit? In odit a itaque est accusamus laborum, nam quis error impedit.
       Distinctio, ipsa. Quia, vero qui! Asperiores quaerat aperiam ullam expedita quis ab tempora odio laboriosam perspiciatis voluptatibus facere repellendus alias et, nihil rerum soluta, inventore tempore? A rem excepturi beatae.
       Natus inventore pariatur, veniam, possimus eaque maxime suscipit accusamus eum tempore aperiam, accusantium id eligendi consectetur quod quo vel reiciendis est deleniti perspiciatis consequuntur! Modi porro facere laudantium ab beatae.
       Architecto vitae ipsum tenetur assumenda laudantium maxime a perspiciatis, doloribus quidem consequatur aperiam vel fugit eaque fugiat iste, unde labore dolor maiores excepturi sed doloremque veniam. Quod debitis iure illum?
       Quibusdam sequi, inventore, doloremque esse error omnis debitis distinctio eum nulla ad odit consectetur, ipsa a nemo reprehenderit excepturi! Impedit nobis esse sunt ut unde inventore qui consequuntur deleniti deserunt.
       Omnis ea quae dignissimos. Animi, nulla? Laboriosam, quo. Accusantium sequi ex esse atque. Rem, tenetur, veniam consequuntur quaerat aliquam sed libero vitae at dolor accusamus iste laudantium ipsum placeat provident!
       Tenetur iste nihil accusamus libero labore veritatis vero ipsam at alias error accusantium, eaque repellendus doloremque consequuntur, quis animi non fugiat impedit earum inventore recusandae? Sunt corrupti maiores nulla aliquam.
       Distinctio, sint minus tenetur consequatur numquam culpa, quia labore ducimus quasi modi, deleniti aliquid? Numquam quod ut et excepturi illum explicabo, ducimus consequatur repellat maiores molestiae esse, magnam dicta rem.
       Fugit accusantium repudiandae ad eligendi eum impedit, exercitationem laborum provident molestiae rerum deserunt dolore temporibus molestias delectus aut eos dignissimos consequuntur eaque quibusdam officia alias aperiam repellat. Obcaecati, dolorem similique!
       Esse quasi fuga commodi, itaque nulla quidem cum unde architecto velit iste dolore, ipsam assumenda earum? Fugit ratione culpa temporibus ipsa totam aspernatur, quibusdam libero, non vero eos, officiis amet!
       Quia ducimus consectetur ad voluptatibus officiis. Reprehenderit, qui? Totam ratione libero assumenda aut eveniet molestiae fugiat, saepe alias hic, minus quam, maxime unde maiores. Tempore excepturi voluptates quo qui suscipit.
       Odio, ullam omnis dolorum at officia rem ad natus, laborum quasi nobis iusto amet dolor incidunt voluptates harum! Quos facilis provident, repudiandae soluta perspiciatis quidem alias voluptatem eveniet voluptatum porro.
       Alias aperiam labore adipisci dignissimos, amet id illum delectus magni, cumque totam dicta voluptatibus doloribus iure sunt consectetur, vero cum aut ex? Quia nesciunt beatae omnis tempora fugiat quae sunt!
       Obcaecati aperiam magnam cupiditate quasi inventore aliquid! Architecto, officia molestiae repellat dolorem esse explicabo nemo vero veritatis! Provident velit, itaque laboriosam et perferendis ex ratione quae odio eveniet dolore earum!
       Repellat nam assumenda ex officia harum necessitatibus nemo aut, maiores quisquam dolor excepturi placeat voluptas commodi laudantium tempora odit sint ea magni sapiente voluptates, dolorum quidem, fugit cupiditate? Esse, molestias.
       Possimus officiis vel ad maxime commodi corrupti nihil rerum, iusto deserunt earum totam veritatis nesciunt magnam delectus numquam quae. Nostrum, neque. Voluptatum sit sunt aut sequi placeat aperiam illo incidunt!
       Error quis sed fugit quaerat quod necessitatibus, unde, reiciendis saepe pariatur molestias similique. Sequi voluptatem at ullam, nostrum ea nam dignissimos quis libero eos ipsum suscipit cumque tempora atque ratione.
       Quo ab consequuntur impedit tempore corporis maiores explicabo pariatur error quasi iure aliquam esse suscipit eaque nobis sunt et doloribus amet at perferendis quibusdam nemo recusandae veniam, in ipsam. Tenetur.
       Delectus sed pariatur tempora excepturi inventore ea laborum cupiditate nulla consequuntur quis, rem at facere neque blanditiis voluptates eius eum? Magni nisi reiciendis eveniet similique ipsum laborum facere quae soluta?
       Quam velit ipsam ipsum tenetur iste omnis natus, quia, porro tempore et odio. Dolore excepturi provident assumenda obcaecati aperiam corrupti atque, molestiae iure fuga quasi suscipit alias nesciunt eius numquam.
       Molestias, reiciendis? Ratione accusamus laboriosam molestias veniam vitae qui culpa amet nobis voluptates recusandae velit provident odio, iure suscipit eum repellendus quis excepturi ut deserunt tempora debitis voluptatem. Ad, facilis!
       Eius harum non libero, sunt saepe numquam ducimus, porro recusandae optio sit necessitatibus ad ut vero ratione iste ipsam accusamus voluptates dicta nostrum laudantium sequi error labore. Atque, architecto dolor?
       Maxime modi nam necessitatibus optio saepe velit nemo sapiente tempore odit? Aspernatur facere, nobis porro reprehenderit qui nihil placeat minus, magni inventore nam alias sunt asperiores rerum. Fugiat, rem eius.
       Non magni molestias, fuga modi deleniti beatae accusantium dolor vel dignissimos neque, fugit molestiae! Ut suscipit neque nobis minima perspiciatis, enim tempora necessitatibus ipsa beatae reiciendis, placeat voluptates quos quo!
       Quos reprehenderit, dolores, est assumenda aspernatur distinctio nulla quis architecto error, ratione laborum fuga vel labore doloremque quo nisi odit natus consectetur. Beatae, voluptatum consequuntur ad voluptate dolorum porro saepe?
       Sit placeat, repudiandae dolor mollitia reiciendis omnis iusto fugiat sapiente incidunt eos. Perferendis suscipit voluptatibus in maxime voluptatum ipsa dolorem beatae optio, mollitia impedit cum vitae accusantium laboriosam eos vel!
       Recusandae, maxime commodi. Repudiandae amet beatae sed temporibus dolorum aut veritatis quis enim dicta incidunt saepe, sit a cum earum, expedita labore voluptatibus, accusantium harum totam veniam natus quibusdam! Consequatur.
       Magni aut ab sapiente veritatis suscipit culpa dolorum illum fuga ipsum quae et quaerat asperiores tenetur, quas eaque. Saepe, ipsum assumenda velit quasi neque facilis hic consequatur perferendis obcaecati expedita.
       Quidem hic impedit quibusdam id aliquid reprehenderit praesentium accusantium soluta, non eveniet voluptatibus nihil consequuntur quis eum vel nemo provident explicabo, deleniti ea, facilis sunt similique! Minus sint temporibus eligendi.
       Atque rerum veritatis omnis facere incidunt soluta maiores, vitae dolores dolorum consectetur error libero labore aut itaque, eius pariatur similique sed iure ea exercitationem. Eius, necessitatibus. Quaerat adipisci soluta ad.
       Neque deserunt unde numquam voluptates natus ex obcaecati commodi earum, vitae deleniti nam temporibus doloremque possimus provident quam ducimus beatae reiciendis quasi iste. Voluptates modi quis debitis tempore architecto labore!
       Nostrum, error labore nisi odit nemo aliquid quibusdam iste saepe, illum a modi est, incidunt magnam! Eveniet minima sunt hic ut quas! Laudantium quos impedit, magni incidunt nemo provident quae!
       Dignissimos cum exercitationem illo ullam libero quae suscipit qui quasi eius nesciunt quisquam, pariatur numquam perferendis nulla sit odit, perspiciatis natus animi. Pariatur quam veniam impedit nulla voluptates deserunt veritatis?
       Nisi est esse omnis recusandae incidunt. Perferendis, facilis? Assumenda voluptates praesentium debitis dolorem dolorum vel quis esse, dolores iste incidunt ducimus ullam fugiat vitae deserunt repellendus ut illo natus. Odit!
       Nulla repudiandae, voluptates ab voluptatem id dolores, cum atque recusandae sunt, vero similique quae excepturi culpa? Quasi dicta saepe ducimus dignissimos. Sequi sed consequuntur, pariatur doloremque dolorem quibusdam qui dicta!
       Dolor nam repellendus aperiam, eum qui ex similique facere fuga ipsum adipisci et inventore aliquid exercitationem laborum veniam. Repudiandae eius cum fuga doloribus quidem officia iure saepe, molestias commodi non!
       Pariatur asperiores dignissimos eaque ullam mollitia nam voluptatem praesentium possimus fuga placeat. Vitae laudantium cumque, iusto delectus obcaecati reiciendis inventore doloremque magni porro earum sit! Itaque voluptas vero rem amet.
       Tempora tenetur unde, sequi dolores laborum deleniti neque ad recusandae minus dignissimos, sunt fugiat asperiores! Cum odio dignissimos hic, quis voluptates obcaecati! Quo ullam neque cupiditate facilis doloribus quaerat officia?
       Molestiae, aliquam aspernatur iure natus iusto eum deleniti sapiente, adipisci quaerat culpa eius. Modi natus dicta fuga temporibus quos nostrum tempore facilis provident possimus, ab tempora debitis illo, iste beatae.
       Labore reprehenderit laborum nisi maxime exercitationem amet minus quas earum dolores quidem! Sapiente soluta praesentium amet, eligendi itaque consectetur, cupiditate deleniti facere vero aut, provident reiciendis nobis doloribus. Doloribus, aliquid.
       Veniam fuga ullam maxime repudiandae officia amet! Laborum cupiditate temporibus, enim numquam ducimus doloribus beatae reiciendis, voluptatibus sint sapiente voluptate esse sequi eius sed? Tempore at culpa ducimus nemo excepturi!
       Saepe, ullam. Voluptate commodi ab incidunt atque hic quasi delectus maxime tenetur porro accusantium mollitia vitae obcaecati, repellendus quo facere. Est fuga eligendi nobis deleniti quo porro dolore voluptas delectus.
       Commodi, autem officia vero nihil sapiente reiciendis molestiae eius nemo suscipit corporis ducimus ea dolore quidem quasi quisquam mollitia et natus consequuntur placeat, impedit ullam deserunt voluptate. Velit, itaque dolore.
       Fugiat ea blanditiis quaerat ullam cumque ad, vel quibusdam assumenda facilis dolorem, est nesciunt dicta quae numquam recusandae eaque beatae tenetur veritatis. Dolorum veniam, explicabo culpa commodi odit doloremque hic.
       Veritatis sapiente corporis excepturi nesciunt iure quae quia et maxime tenetur, earum quis inventore voluptatibus impedit neque ea saepe quidem? Enim sed maiores modi nostrum aliquid labore nam aperiam placeat.
       Aliquid delectus nulla beatae minima qui quas, eveniet voluptate, voluptates similique facere perferendis quis quia perspiciatis quo ratione inventore esse dolorum! Sunt, cupiditate necessitatibus. Magni delectus vero omnis ipsam nemo.
       Eius tempore voluptas voluptates minus, delectus sit nulla, repudiandae consectetur perferendis ipsum dicta quam quas totam dolorum sint neque. Rem a odit harum veniam ex iure possimus amet illo voluptatum.
       Deserunt, assumenda aspernatur sapiente natus aliquid aut facilis iste veniam tempore, sed aliquam necessitatibus sequi ad molestiae officiis quaerat qui porro nemo! Expedita velit atque est facilis? Hic, temporibus dolore?
       Fugit officia incidunt nihil doloribus laboriosam animi, rem sed voluptatem reprehenderit impedit alias, laborum eius blanditiis unde officiis. Explicabo id ut vero recusandae eligendi ducimus voluptatum esse odio ratione adipisci!
       Maxime, temporibus praesentium placeat perspiciatis excepturi in sequi enim aut tempora dolores, aperiam aliquam qui optio architecto quibusdam laudantium omnis. Aliquid fugiat ratione in sed, quo itaque modi cumque eius?
       Nostrum quod, quae magni, molestias laboriosam repellendus, rerum accusamus corrupti modi accusantium sunt eligendi. Optio maxime, sed consequatur quo quibusdam sint repudiandae rem illum illo saepe eveniet recusandae asperiores sit.
       Iure odio iusto neque, veniam omnis sed non perspiciatis animi, adipisci saepe facere sequi amet voluptates voluptate rerum tempore possimus eius! Saepe placeat doloribus, aspernatur distinctio commodi corrupti quas voluptate.
       Velit et dolores similique voluptatum accusantium, sapiente nemo consequatur, error qui illo inventore est molestiae fugiat commodi obcaecati magnam facere magni reiciendis quis! Repellendus obcaecati non excepturi ipsa! Voluptatibus, nulla?
       Facere error labore quaerat iusto quia amet dicta voluptas odit, perspiciatis doloribus, odio numquam animi dignissimos mollitia. Nobis vitae quos quaerat natus rem, in similique recusandae officia dolore ducimus dicta.
       Ea totam recusandae non id minus, accusamus sed rem iste, animi molestias perferendis veniam qui vitae sequi in facilis. Velit nihil necessitatibus autem ullam nemo ducimus odit ut unde dolorem!
       Ut enim quo veritatis corporis nostrum possimus rem! Eligendi similique aliquid culpa, quibusdam iusto suscipit, sequi deleniti quis non atque fugiat voluptatibus dolorum exercitationem nam. Itaque deleniti labore obcaecati aut.
       Beatae perspiciatis qui asperiores provident debitis corrupti libero, cupiditate vero dolore autem modi placeat dolorum doloremque, nulla nemo nostrum eaque at. Sequi nulla ea, magnam quis delectus deleniti libero commodi.
       In dolores sit atque porro possimus optio, temporibus ex ipsa, voluptatum debitis nesciunt saepe recusandae quod similique fuga ratione labore neque dolor iure harum sunt. A voluptatem fuga sequi optio.
       Possimus, quis cupiditate dolore perferendis officiis a voluptatem voluptas provident obcaecati pariatur doloribus at praesentium laudantium illo corrupti repudiandae ad ea aperiam dignissimos! Nulla quam aperiam in incidunt, necessitatibus unde.
       Quis, voluptates nesciunt. Et placeat aliquam doloremque nulla aut aspernatur odit quam necessitatibus error, quo velit at repudiandae laudantium minima ea rem, excepturi totam libero magnam est odio! Eius, harum.
       Odit rerum debitis fugiat repellat assumenda exercitationem quas sint, blanditiis eum explicabo perferendis consectetur, nesciunt iure, provident iusto possimus voluptatem. Possimus harum voluptatibus maxime tenetur, atque cum alias fugiat voluptatum.
       Neque, aliquam, libero, voluptatum ipsa blanditiis vero saepe voluptate quia placeat velit accusamus hic enim adipisci architecto omnis repellat quod quis sit perspiciatis aut accusantium! Tempora consequatur perspiciatis nesciunt officiis.
       Eveniet excepturi enim animi quisquam sunt ad voluptatum illum sint facere, provident modi voluptatem neque minus? Dolore aut, blanditiis veniam cumque sint quia quibusdam exercitationem totam praesentium modi voluptatibus ipsam.</p>
    </div>
  )
}

export default UpdateProduct